export const FETCH_POSTS_ALL = 'FETCH_POSTS_ALL';
export const FETCH_POSTS_ALL_START = 'FETCH_POSTS_ALL_START';
export const FETCH_POSTS_ALL_SUCCESS = 'FETCH_POSTS_ALL_SUCCESS';
export const FETCH_POSTS_ALL_FAIL = 'FETCH_POSTS_ALL_FAIL';