export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_START='FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS='FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL='FETCH_CATEGORIES_FAIL';


export const FETCH_POSTS_ALL = 'FETCH_POSTS_ALL';
export const FETCH_POSTS_ALL_START = 'FETCH_POSTS_ALL_START';
export const FETCH_POSTS_ALL_SUCCESS = 'FETCH_POSTS_ALL_SUCCESS';
export const FETCH_POSTS_ALL_FAIL = 'FETCH_POSTS_ALL_FAIL';

